@startuml
actor Commercial
participant ERP as "Application ERP"
participant Magasin as "Module Magasin"
participant Fournisseur as "Module Fournisseur"
participant Production as "Module Production"
participant Comptabilité as "Module Comptabilité"
participant Dashboard

Commercial -> ERP : Créer commande client
ERP -> Magasin : Vérifier matiére première
Magasin -> ERP : Stock insuffisant
ERP -> Fournisseur : Commander Matière première
Fournisseur -> ERP : Confirmer la commande matière première
Fournisseur -> Magasin : Reception de commande matière première
Magasin -> Magasin : Mettre a jour le stock
Magasin -> ERP : Stock matière première mis a jour
ERP -> Production : Creer commande de production
Production -> Magasin : Mettre a jour le status de production (fini)
Magasin -> Magasin : Mettre a jour le Stock produit
Magasin -> Commercial : Stock produit mis a jour
Commercial -> ERP : confirmation commande avec le client
ERP -> Comptabilité : Generer facture client
Comptabilité -> ERP : facture creé
ERP -> Commercial : imprimer et delivrer facture au client
Commercial -> ERP : Valider la commande client
ERP -> Comptabilité : enregistrement transaction
Comptabilité -> ERP : transaction enregistrée
ERP -> Commercial : Commande cloturé
ERP -> Dashboard : Mettre a jour Dashboard et rapports
@enduml
